#!/bin/bash

current_repo=$(git remote get-url origin | awk -F: '{print $2}' | sed "s/.git//")
number=$1
repo=${2:-$current_repo}

curl -s -L -H "Accept: application/vnd.github.v3+json" -H "Authorization: Token $GHTOKEN"  https://git.dev.box.net/api/v3/repos/$repo/pulls/$number
echo

