#!/bin/bash
bold=`tput bold`
normal=`tput sgr0`
echo -n "${bold}branch :: *"
git rev-parse --abbrev-ref HEAD
echo -n "${normal}"
git --no-pager log -1 --pretty=oneline --abbrev-commit
echo "--------------------- git status -------------------"
git status -s
