#!/bin/bash

branch=$(git rev-parse --abbrev-ref HEAD)
repo_full_name=$(git remote get-url origin | awk -F: '{print $2}' | sed "s/.git//")

if  [ $branch == "master" ] || [ $branch == "dev" ] || [ $branch == "v5-dev" ] ; then
  RED='\033[0;31m'
  NC='\033[0m' #
  echo -e "${RED}Current branch is $branch. Refusing to push to $branch${NC}"
  exit 1
fi

git push -u origin HEAD:refs/heads/$branch
curl -s -L -X POST -H "Accept: application/vnd.github.v3+json" -H "Authorization: Token $GHTOKEN" --data "{
\"title\": \"$(git log -1 --format=%s)\",
\"head\": \"$branch\",
\"base\": \"master\"
}"  https://git.dev.box.net/api/v3/repos/$repo_full_name/pulls
echo

