#!/bin/bash
RED='\033[0;31m'
NOCOLOR='\033[0m' # No Color
if [ "$1" == "staging" ]; then
  ssh fusion-staging01.pod.box.net 'sudo yum -y install --enablerepo=productivity-snapshots fusion'
elif [ "$1" == "all" ]; then
  ssh fusion-staging01.pod.box.net 'sudo yum -y install --enablerepo=productivity-snapshots fusion'
  ssh fusion.pod.box.net 'sudo yum -y install --enablerepo=productivity-snapshots fusion'
else
  echo "$(tput setaf 1)must call release-fusion \"staging\" or release-fusion \"all\"$(tput sgr 0)"
fi
