#!/bin/bash
echo '
127.0.0.1	localhost
127.0.1.1	evan-ThinkPad-T530
127.0.1.1	www.facebook.com
127.0.1.1	facebook.com
127.0.1.1	reddit.com
127.0.1.1	www.reddit.com
127.0.1.1	chess.com
127.0.1.1	www.chess.com
127.0.1.1	youtube.com
127.0.1.1	www.youtube.com
127.0.1.1       watchserieshd.eu
127.0.1.1       www.watchserieshd.eu
127.0.1.1       watchseries-online.eu
127.0.1.1       www.watchseries-online.eu
127.0.1.1       watchseries.lt
127.0.1.1       www.watchseries.lt



The following lines are desirable for IPv6 capable hosts
::1     ip6-localhost ip6-loopback
fe00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
' > /etc/hosts
